# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_antes', models.DecimalField(decimal_places=3, max_digits=6)),
                ('carga_despues', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Auto')),
            ],
            options={
                'db_table': 'Carga',
            },
        ),
        migrations.CreateModel(
            name='Gasolinera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'Gasolinera',
            },
        ),
        migrations.CreateModel(
            name='RatingsGasolinera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('gasolinera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolinera.Gasolinera')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Persona')),
            ],
            options={
                'db_table': 'RatingsGasolinera',
            },
        ),
        migrations.AddField(
            model_name='gasolinera',
            name='ratings_persona',
            field=models.ManyToManyField(through='gasolinera.RatingsGasolinera', to='management.Persona'),
        ),
        migrations.AddField(
            model_name='carga',
            name='gasolinera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolinera.Gasolinera'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsgasolinera',
            unique_together=set([('persona', 'gasolinera')]),
        ),
    ]
