# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.IntegerField()),
                ('year', models.IntegerField()),
                ('motor', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='MarcaAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('logo', models.ImageField(upload_to='marcas_auto')),
            ],
            options={
                'db_table': 'MarcaAuto',
            },
        ),
        migrations.CreateModel(
            name='ModeloAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.MarcaAuto')),
            ],
            options={
                'db_table': 'ModeloAuto',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.ModeloAuto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Persona'),
        ),
    ]
