# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloauto',
            name='capacidad_tanque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='management.Persona'),
        ),
        migrations.AlterField(
            model_name='modeloauto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='auto.MarcaAuto'),
        ),
    ]
