# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20170531_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaauto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas_auto'),
        ),
    ]
